#!/usr/bin/python

################################################################################
#
# cloud-cli
#
# Main entry point for managing and controlling/configuring resources in a cloud
# platform
#
################################################################################

from cli import CLI
import os


MY_PATH = os.path.abspath(os.path.dirname(__file__))
DEFAULT_CFG = os.path.join(MY_PATH, "cli_config.yml")


def main():
    cli = CLI(DEFAULT_CFG)
    cli.init()
    cli.run()


if __name__ == "__main__":
    main()
