#!/usr/bin/python
"""
cloud-cli

Main entry point for managing and controlling/configuring resources in a cloud
platform
"""
import os
from cli import CLI

MY_PATH = os.path.abspath(os.path.dirname(__file__))
DEFAULT_CFG = os.path.join(MY_PATH, "cli_config.yml")

def main():
    """ Runs the cli """
    cli = CLI(DEFAULT_CFG)
    cli.run()


if __name__ == "__main__":
    main()
